In [2]:
from kdm.models import KDMSequentialJointClassModel
import kdm
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_moons
import matplotlib.pyplot as plt
import numpy as np
from keras import metrics
from keras import losses
from keras import optimizers
from keras.models import Model
from keras.layers import Input, Dense
import keras
from pandas import read_csv, DataFrame
import os
os.environ["KERAS_BACKEND"] = "tensorflow"


In [3]:
df = read_csv('iris.csv')

In [4]:
df.head()

sepal length  sepal width  petal length  petal width         type
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [9]:
df['type'] = df['type'].apply(lambda x: [1,0,0] if x == 'Iris-setosa' else [0,1,0] if x == 'Iris-versicolor' else [0,0,1])

In [11]:
df.tail()

sepal length  sepal width  petal length  petal width       type
145           6.7          3.0           5.2          2.3  [0, 0, 1]
146           6.3          2.5           5.0          1.9  [0, 0, 1]
147           6.5          3.0           5.2          2.0  [0, 0, 1]
148           6.2          3.4           5.4          2.3  [0, 0, 1]
149           5.9          3.0           5.1          1.8  [0, 0, 1]

In [23]:

encoded_size = 4
dim_y = 3
encoder = keras.layers.Identity()
n_comp = 150
sequences = [
    {
        'type': 'merge'
    }]
kdm_model = KDMSequentialJointClassModel(encoded_size=encoded_size,
                                         dim_y=dim_y,
                                         encoder=encoder,
                                         n_comp=n_comp,
                                         sequences=sequences,
                                         sigma=0.5)

In [24]:
kdm_model.compile(optimizer=optimizers.Adam(learning_rate=5e-5),
                  loss=losses.sparse_categorical_crossentropy,
                  metrics=[metrics.sparse_categorical_accuracy])

In [52]:
data = []
for row in df.iterrows():
    y = row[1]['type']
    x = [row[1]['sepal length'], row[1]['sepal width'], row[1]['petal length'], row[1]['petal width']]
    data.append((x, y))
    

In [53]:
data

[([5.1, 3.5, 1.4, 0.2], [1, 0, 0]),
 ([4.9, 3.0, 1.4, 0.2], [1, 0, 0]),
 ([4.7, 3.2, 1.3, 0.2], [1, 0, 0]),
 ([4.6, 3.1, 1.5, 0.2], [1, 0, 0]),
 ([5.0, 3.6, 1.4, 0.2], [1, 0, 0]),
 ([5.4, 3.9, 1.7, 0.4], [1, 0, 0]),
 ([4.6, 3.4, 1.4, 0.3], [1, 0, 0]),
 ([5.0, 3.4, 1.5, 0.2], [1, 0, 0]),
 ([4.4, 2.9, 1.4, 0.2], [1, 0, 0]),
 ([4.9, 3.1, 1.5, 0.1], [1, 0, 0]),
 ([5.4, 3.7, 1.5, 0.2], [1, 0, 0]),
 ([4.8, 3.4, 1.6, 0.2], [1, 0, 0]),
 ([4.8, 3.0, 1.4, 0.1], [1, 0, 0]),
 ([4.3, 3.0, 1.1, 0.1], [1, 0, 0]),
 ([5.8, 4.0, 1.2, 0.2], [1, 0, 0]),
 ([5.7, 4.4, 1.5, 0.4], [1, 0, 0]),
 ([5.4, 3.9, 1.3, 0.4], [1, 0, 0]),
 ([5.1, 3.5, 1.4, 0.3], [1, 0, 0]),
 ([5.7, 3.8, 1.7, 0.3], [1, 0, 0]),
 ([5.1, 3.8, 1.5, 0.3], [1, 0, 0]),
 ([5.4, 3.4, 1.7, 0.2], [1, 0, 0]),
 ([5.1, 3.7, 1.5, 0.4], [1, 0, 0]),
 ([4.6, 3.6, 1.0, 0.2], [1, 0, 0]),
 ([5.1, 3.3, 1.7, 0.5], [1, 0, 0]),
 ([4.8, 3.4, 1.9, 0.2], [1, 0, 0]),
 ([5.0, 3.0, 1.6, 0.2], [1, 0, 0]),
 ([5.0, 3.4, 1.6, 0.4], [1, 0, 0]),
 ([5.2, 3.5, 1.5, 0.2], [1, 

In [54]:
input = np.array([x for x, y in data])
output = np.array([y for x, y in data])
y_out = np.array([int(np.argmax(y)) for y in output])

In [55]:
kdm_model.init_components(np.array(input), np.array(output),
                                init_sigma=True, sigma_mult=0.5, super_index=0, index=0)

In [56]:
y_out

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [57]:
input

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [58]:
check_1 = kdm_model.evaluate(np.array(input), np.array(y_out))


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1650 - sparse_categorical_accuracy: 0.9618  


In [59]:

print('Full Dataset loss:', check_1[0])
print('Full Dataset accuracy:', check_1[1])

Full Dataset loss: 0.24461616575717926
Full Dataset accuracy: 0.9399999976158142


## Training Power

In [90]:
combined_y = np.array([[int(np.argmax(y)), y] for y in output])

/var/folders/2s/yq898nms72b5qxqbwz_hx8j80000gn/T/ipykernel_12702/2480946680.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  combined_y = np.array([[int(np.argmax(y)), y] for y in output])


In [91]:
combined_y

array([[0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0,

In [112]:
X_train, X_test, y_train, y_test = train_test_split(
    input, combined_y, test_size=0.4, random_state=42)

In [113]:
print(len(X_train))
len(X_test)

90


60

In [123]:

encoded_size = 4
dim_y = 3
encoder = keras.layers.Identity()
n_comp = 90
sequences = [
    {
        'type': 'merge'
    }]
kdm_model = KDMSequentialJointClassModel(encoded_size=encoded_size,
                                         dim_y=dim_y,
                                         encoder=encoder,
                                         n_comp=n_comp,
                                         sequences=sequences,
                                         sigma=0.5)

In [125]:
from tensorflow.keras import optimizers, losses

kdm_model.compile(optimizer=optimizers.Adam(learning_rate=5e-5),
              loss=losses.sparse_categorical_crossentropy,
              metrics=[metrics.sparse_categorical_accuracy,])


In [126]:
real_out = np.array([y[1] for y in y_train])

kdm_model.init_components(np.array(X_train), np.array(real_out),
                                init_sigma=True, sigma_mult=0.5, super_index=0, index=0)

In [127]:
check_full = kdm_model.evaluate(np.array(input), np.array(y_out))

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - loss: 0.1668 - sparse_categorical_accuracy: 0.9688


In [128]:
print('Full Dataset loss:', check_full[0])
print('Full Dataset accuracy:', check_full[1])

Full Dataset loss: 0.24101483821868896
Full Dataset accuracy: 0.95333331823349


In [129]:
y_out_test = np.array([y[0] for y in y_test])

In [130]:
check_test = kdm_model.evaluate(np.array(X_test), np.array(y_out_test))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2078 - sparse_categorical_accuracy: 1.0000 


In [131]:
print('Test Dataset loss:', check_test[0])
print('Test Dataset accuracy:', check_test[1])

Test Dataset loss: 0.20930203795433044
Test Dataset accuracy: 1.0
