- 1	Muscle loss
- 2	2-Oxoglutarate
- 3	3-Aminoisobutyrate
- 4	Adipate
- 5	Betaine
- 6	Creatinine
- 7	Hypoxanthine
- 8	N,N-Dimethylglycine




- 1	3
- 1	4
- 1	5
- 1	7
- 2	7
- 6	7
- 8	5


Directed GRAPH of the example - Comparison Accuracy 0.7532

In [1]:
from kdm.models import KDMSequentialJointClassModel
import kdm
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_moons
import matplotlib.pyplot as plt
import numpy as np
from keras import metrics
from keras import losses
from keras import optimizers
from keras.models import Model
from keras.layers import Input, Dense
import keras
from pandas import read_csv, DataFrame
import os
os.environ["KERAS_BACKEND"] = "tensorflow"


In [2]:
df = read_csv('cachexia.csv')

In [3]:
df.head()

Patient ID Muscle loss  1,6-Anhydro-beta-D-glucose  1-Methylnicotinamide  \
0      PIF_178    cachexic                       40.85                 65.37   
1      PIF_087    cachexic                       62.18                340.36   
2      PIF_090    cachexic                      270.43                 64.72   
3  NETL_005_V1    cachexic                      154.47                 52.98   
4      PIF_115    cachexic                       22.20                 73.70   

   2-Aminobutyrate  2-Hydroxyisobutyrate  2-Oxoglutarate  3-Aminoisobutyrate  \
0            18.73                 26.05           71.52             1480.30   
1            24.29                 41.68           67.36              116.75   
2            12.18                 65.37           23.81               14.30   
3           172.43                 74.44         1199.91              555.57   
4            15.64                 83.93           33.12               29.67   

   3-Hydroxybutyrate  3-Hydroxyisovalerate  ...  Tryptophan  Tyrosine  Uracil  \
0              56.83                 10.07  ...      259.82    290.03  111.05   
1              43.82                 79.84  ...       83.10    167.34   46.99   
2               5.64                 23.34  ...       82.27     60.34   31.50   
3             175.91                 25.03  ...      235.10    323.76   30.57   
4              76.71                 69.41  ...      103.54    142.59   44.26   

   Valine   Xylose  cis-Aconitate  myo-Inositol  trans-Aconitate  \
0   86.49    72.24         237.46        135.64            51.94   
1  109.95   192.48         333.62        376.15           217.02   
2   59.15  2164.62         330.30         86.49            58.56   
3  102.51   125.21        1863.11        247.15            75.94   
4  160.77   186.79         101.49        749.95            98.49   

   pi-Methylhistidine  tau-Methylhistidine  
0              157.59               160.77  
1              307.97               130.32  
2              145.47                83.93  
3              249.64               254.68  
4               84.77                79.84  

[5 rows x 65 columns]

In [4]:
# finish just Muscle loss, 3-Aminoisobutyrate, Adipate, Betaine and Hypoxanthine

filtered_df = df[['Muscle loss', '3-Aminoisobutyrate', 'Adipate', 'Betaine', 'Hypoxanthine']]

In [5]:
filtered_df.head()

Muscle loss  3-Aminoisobutyrate  Adipate  Betaine  Hypoxanthine
0    cachexic             1480.30    38.09   109.95         97.51
1    cachexic              116.75   327.01   244.69         82.27
2    cachexic               14.30   131.63   116.75        114.43
3    cachexic              555.57   144.03   278.66        223.63
4    cachexic               29.67    15.03   391.51         66.69

In [6]:
# transform musche loss in 0-1
filtered_df['Muscle loss'] = filtered_df['Muscle loss'].apply(lambda x: 1 if x == 'cachexic' else 0)

/var/folders/2s/yq898nms72b5qxqbwz_hx8j80000gn/T/ipykernel_61790/903024324.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Muscle loss'] = filtered_df['Muscle loss'].apply(lambda x: 1 if x == 'cachexic' else 0)


In [7]:
filtered_df.head()

Muscle loss  3-Aminoisobutyrate  Adipate  Betaine  Hypoxanthine
0            1             1480.30    38.09   109.95         97.51
1            1              116.75   327.01   244.69         82.27
2            1               14.30   131.63   116.75        114.43
3            1              555.57   144.03   278.66        223.63
4            1               29.67    15.03   391.51         66.69

## Prediction Power

In [8]:

encoded_size = 4
dim_y = 2
encoder = keras.layers.Identity()
n_comp = 77
sequences = [
    {
        'type': 'merge'
    },
    ]
kdm_model = KDMSequentialJointClassModel(encoded_size=encoded_size,
                                         dim_y=dim_y,
                                         encoder=encoder,
                                         n_comp=n_comp,
                                         sequences=sequences,
                                         sigma=0.5)

In [9]:
kdm_model.compile(optimizer=optimizers.Adam(learning_rate=5e-5),
                  loss=losses.sparse_categorical_crossentropy,
                  metrics=[metrics.sparse_categorical_accuracy])

In [10]:
data = []
for row in filtered_df.iterrows():
    y = int(row[1]['Muscle loss'])
    x = row[1][1:].values
    data.append((x, y))
    

In [11]:
print(data)

[(array([1480.3 ,   38.09,  109.95,   97.51]), 1), (array([116.75, 327.01, 244.69,  82.27]), 1), (array([ 14.3 , 131.63, 116.75, 114.43]), 1), (array([555.57, 144.03, 278.66, 223.63]), 1), (array([ 29.67,  15.03, 391.51,  66.69]), 1), (array([17.46, 25.28, 66.69, 62.8 ]), 1), (array([ 56.26,   8.41, 149.9 ,  25.79]), 1), (array([ 8.67,  3.53, 15.33, 20.7 ]), 1), (array([17.99,  8.25, 31.19, 80.64]), 1), (array([ 57.97,  14.59, 149.9 ,  43.82]), 1), (array([ 93.69,  18.54, 219.2 ,  40.85]), 1), (array([105.64, 259.82, 137.  ,  33.78]), 1), (array([  8.08,  11.02, 167.34, 162.39]), 1), (array([43.38,  9.03, 56.83, 36.6 ]), 1), (array([ 2.97,  3.16, 41.68,  4.22]), 1), (array([6.36, 4.81, 4.06, 5.05]), 1), (array([ 31.82,  22.87, 157.59,  29.37]), 1), (array([16.12, 15.8 , 78.26, 92.76]), 1), (array([79.04, 12.43, 60.34, 42.52]), 1), (array([18.73, 20.49, 68.72, 23.81]), 1), (array([ 50.4 ,  18.54, 131.63,  45.6 ]), 1), (array([104.58,  28.79, 170.72, 165.67]), 1), (array([63.43, 23.1 , 6

In [12]:
input = np.array([x for x, y in data])
y_out = np.array([y for x, y in data])
output = np.array([[0,1] if y == 1 else [1,0] for x, y in data])

In [13]:
input

array([[1480.3 ,   38.09,  109.95,   97.51],
       [ 116.75,  327.01,  244.69,   82.27],
       [  14.3 ,  131.63,  116.75,  114.43],
       [ 555.57,  144.03,  278.66,  223.63],
       [  29.67,   15.03,  391.51,   66.69],
       [  17.46,   25.28,   66.69,   62.8 ],
       [  56.26,    8.41,  149.9 ,   25.79],
       [   8.67,    3.53,   15.33,   20.7 ],
       [  17.99,    8.25,   31.19,   80.64],
       [  57.97,   14.59,  149.9 ,   43.82],
       [  93.69,   18.54,  219.2 ,   40.85],
       [ 105.64,  259.82,  137.  ,   33.78],
       [   8.08,   11.02,  167.34,  162.39],
       [  43.38,    9.03,   56.83,   36.6 ],
       [   2.97,    3.16,   41.68,    4.22],
       [   6.36,    4.81,    4.06,    5.05],
       [  31.82,   22.87,  157.59,   29.37],
       [  16.12,   15.8 ,   78.26,   92.76],
       [  79.04,   12.43,   60.34,   42.52],
       [  18.73,   20.49,   68.72,   23.81],
       [  50.4 ,   18.54,  131.63,   45.6 ],
       [ 104.58,   28.79,  170.72,  165.67],
       [  

In [14]:
output

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1,

In [15]:
kdm_model.init_components(np.array(input), np.array(output),
                                init_sigma=True, sigma_mult=0.5, super_index=0, index=0)

In [16]:
check_1 = kdm_model.evaluate(np.array(input), np.array(y_out))


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4964 - sparse_categorical_accuracy: 0.8037  


In [17]:

print('Full Dataset loss:', check_1[0])
print('Full Dataset accuracy:', check_1[1])

Full Dataset loss: 0.5318797826766968
Full Dataset accuracy: 0.7792207598686218


## Training Power

In [32]:
combined_y = np.array([[y, [0,1]] if y == 1 else [y, [1,0]] for x, y in data])

/var/folders/2s/yq898nms72b5qxqbwz_hx8j80000gn/T/ipykernel_61790/3391731745.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  combined_y = np.array([[y, [0,1]] if y == 1 else [y, [1,0]] for x, y in data])


In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    input, combined_y, test_size=0.1, random_state=42)

In [34]:
len(X_train)

69

In [35]:

encoded_size = 4
dim_y = 2
encoder = keras.layers.Identity()
n_comp = 69
sequences = [
    {
        'type': 'merge'
    },
    ]
kdm_model = KDMSequentialJointClassModel(encoded_size=encoded_size,
                                         dim_y=dim_y,
                                         encoder=encoder,
                                         n_comp=n_comp,
                                         sequences=sequences,
                                         sigma=0.5)

kdm_model.compile(optimizer=optimizers.Adam(learning_rate=5e-7),
                  loss=losses.sparse_categorical_crossentropy,
                  metrics=[metrics.sparse_categorical_accuracy])

In [36]:
y_train

array([[0, list([1, 0])],
       [1, list([0, 1])],
       [0, list([1, 0])],
       [0, list([1, 0])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [0, list([1, 0])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [0, list([1, 0])],
       [0, list([1, 0])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [0, list([1, 0])],
       [1, list([0, 1])],
       [0, list([1, 0])],
       [0, list([1, 0])],
       [0, list([1, 0])],
       [1, list([0, 1])],
       [0, list([1, 0])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [0, list([1, 0])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [0, list([1, 0])],
       [1, list([0, 1])],
       [1, list([0, 1])],
       [0, l

In [37]:
real_out = np.array([y[1] for y in y_train])



In [31]:
kdm_model.init_components(np.array(X_train), np.array(real_out),
                                init_sigma=True, sigma_mult=0.5, super_index=0, index=0)

In [38]:
check_full = kdm_model.evaluate(np.array(input), np.array(y_out))

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6931 - sparse_categorical_accuracy: 0.2612      


In [39]:
print('Full Dataset loss:', check_full[0])
print('Full Dataset accuracy:', check_full[1])

Full Dataset loss: 0.6931471824645996
Full Dataset accuracy: 0.3896103799343109


In [40]:
check_test = kdm_model.evaluate(np.array(X_test), np.array([y[0] for y in y_test]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6931 - sparse_categorical_accuracy: 0.3750


In [41]:
print('Test loss:', check_test[0])
print('Test accuracy:', check_test[1])

Test loss: 0.6931471824645996
Test accuracy: 0.375


In [48]:
history = kdm_model.fit(
    np.array(X_train),  # Your training data
    np.array(y_out),  # Your training labels
    batch_size=2,
    epochs=500, 
    verbose=1,  # Detailed logging
    validation_split=0.1,  # Explicit validation data
    shuffle=True  # Shuffle the data
)

Epoch 1/500
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6901 - sparse_categorical_accuracy: 0.7676 - val_loss: 0.6989 - val_sparse_categorical_accuracy: 0.0000e+00
Epoch 2/500
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 732us/step - loss: 0.6900 - sparse_categorical_accuracy: 0.7748 - val_loss: 0.6989 - val_sparse_categorical_accuracy: 0.0000e+00
Epoch 3/500
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - loss: 0.6900 - sparse_categorical_accuracy: 0.7734 - val_loss: 0.6989 - val_sparse_categorical_accuracy: 0.0000e+00
Epoch 4/500
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - loss: 0.6904 - sparse_categorical_accuracy: 0.7404 - val_loss: 0.6990 - val_sparse_categorical_accuracy: 0.0000e+00
Epoch 5/500
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - loss: 0.6896 - sparse_categorical_accuracy: 0.8085 - val_loss: 0.6990 - val_sparse_categorical_accuracy: 0.0000e+00
Epoch 6/500
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - loss: 0.6908 - sparse_categorical_accuracy: 0.7035 - val_loss: 0.6990 - val_sparse_categoric

In [46]:

check_full = kdm_model.evaluate(np.array(input), np.array(y_out))
check_test = kdm_model.evaluate(np.array(X_test), np.array([y[0] for y in y_test]))


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6905 - sparse_categorical_accuracy: 0.7388
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6917 - sparse_categorical_accuracy: 0.6250


In [49]:

print('Full Dataset loss:', check_full[0])
print('Full Dataset accuracy:', check_full[1])


print('Test loss:', check_test[0])
print('Test accuracy:', check_test[1])


Full Dataset loss: 0.6919097900390625
Full Dataset accuracy: 0.6103895902633667
Test loss: 0.6917439699172974
Test accuracy: 0.625
